##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.10.0-B14] date: [Wed Sep 02 17:45:38 CEST 2020] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = mx_build

######################################
# source
######################################
# C sources
C_SOURCES =  \
cubemx_test/main.c \
cubemx_test/printf.c \
cubemx_test/stm32f7xx_it.c \
cubemx_test/stm32f7xx_hal_msp.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart_ex.c \
cubemx_test/system_stm32f7xx.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
cubemx_test/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c 

# ASM sources
ASM_SOURCES =  \
cubemx_test/startup_stm32f767xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F767xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-Icubemx_test \
-Icubemx_test/STM32F7xx_HAL_Driver/Inc \
-Icubemx_test/STM32F7xx_HAL_Driver/Inc/Legacy \
-Icubemx_test/CMSIS/Device/ST/STM32F7xx/Include \
-Icubemx_test/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = cubemx_test/STM32F767ZITx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/memory.map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/firmware.elf $(BUILD_DIR)/firmware.hex $(BUILD_DIR)/firmware.bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/firmware.elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

# It is expected that a openocd.cfg file is in project folder
flash: $(BUILD_DIR)/firmware.bin
	@printf "  OPENOCD\t$<\n"
	openocd

monitor: $(BUILD_DIR)/firmware.bin
	@printf "  OPENOCD\t$<\n"
	openocd
	@printf "  MINICOM\t$<\n"
	minicom

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)
.PHONY: all clean flash monitor

# *** EOF ***
