# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := mbed


# Project settings
###############################################################################
# Objects and Paths

#OBJECTS += ./mbed-os/cmsis/TARGET_CORTEX_M/mbed_tz_context.o
#OBJECTS += ./mbed-os/drivers/source/AnalogIn.o
#OBJECTS += ./mbed-os/drivers/source/AnalogOut.o
#OBJECTS += ./mbed-os/drivers/source/BusIn.o
#OBJECTS += ./mbed-os/drivers/source/BusInOut.o
#OBJECTS += ./mbed-os/drivers/source/BusOut.o
#OBJECTS += ./mbed-os/drivers/source/CAN.o
#OBJECTS += ./mbed-os/drivers/source/DigitalIn.o
#OBJECTS += ./mbed-os/drivers/source/DigitalInOut.o
#OBJECTS += ./mbed-os/drivers/source/DigitalOut.o
#OBJECTS += ./mbed-os/drivers/source/Ethernet.o
#OBJECTS += ./mbed-os/drivers/source/FlashIAP.o
#OBJECTS += ./mbed-os/drivers/source/I2C.o
#OBJECTS += ./mbed-os/drivers/source/I2CSlave.o
#OBJECTS += ./mbed-os/drivers/source/InterruptIn.o
#OBJECTS += ./mbed-os/drivers/source/InterruptManager.o
#OBJECTS += ./mbed-os/drivers/source/MbedCRC.o
#OBJECTS += ./mbed-os/drivers/source/PortIn.o
#OBJECTS += ./mbed-os/drivers/source/PortInOut.o
#OBJECTS += ./mbed-os/drivers/source/PortOut.o
#OBJECTS += ./mbed-os/drivers/source/PwmOut.o
#OBJECTS += ./mbed-os/drivers/source/QSPI.o
#OBJECTS += ./mbed-os/drivers/source/RawSerial.o
#OBJECTS += ./mbed-os/drivers/source/ResetReason.o
#OBJECTS += ./mbed-os/drivers/source/SPI.o
#OBJECTS += ./mbed-os/drivers/source/SPISlave.o
#OBJECTS += ./mbed-os/drivers/source/Serial.o
#OBJECTS += ./mbed-os/drivers/source/SerialBase.o
#OBJECTS += ./mbed-os/drivers/source/SerialWireOutput.o
#OBJECTS += ./mbed-os/drivers/source/TableCRC.o
#OBJECTS += ./mbed-os/drivers/source/Ticker.o
#OBJECTS += ./mbed-os/drivers/source/Timeout.o
#OBJECTS += ./mbed-os/drivers/source/Timer.o
#OBJECTS += ./mbed-os/drivers/source/TimerEvent.o
#OBJECTS += ./mbed-os/drivers/source/UARTSerial.o
#OBJECTS += ./mbed-os/drivers/source/Watchdog.o
#OBJECTS += ./mbed-os/features/storage/blockdevice/BufferedBlockDevice.o
#OBJECTS += ./mbed-os/features/storage/blockdevice/ChainingBlockDevice.o
#OBJECTS += ./mbed-os/features/storage/blockdevice/ExhaustibleBlockDevice.o
#OBJECTS += ./mbed-os/features/storage/blockdevice/FlashSimBlockDevice.o
#OBJECTS += ./mbed-os/features/storage/blockdevice/HeapBlockDevice.o
#OBJECTS += ./mbed-os/features/storage/blockdevice/MBRBlockDevice.o
#OBJECTS += ./mbed-os/features/storage/blockdevice/ObservingBlockDevice.o
#OBJECTS += ./mbed-os/features/storage/blockdevice/ProfilingBlockDevice.o
#OBJECTS += ./mbed-os/features/storage/blockdevice/ReadOnlyBlockDevice.o
#OBJECTS += ./mbed-os/features/storage/blockdevice/SlicingBlockDevice.o
#OBJECTS += ./mbed-os/hal/LowPowerTickerWrapper.o
#OBJECTS += ./mbed-os/hal/mbed_critical_section_api.o
#OBJECTS += ./mbed-os/hal/mbed_flash_api.o
#OBJECTS += ./mbed-os/hal/mbed_gpio.o
#OBJECTS += ./mbed-os/hal/mbed_gpio_irq.o
#OBJECTS += ./mbed-os/hal/mbed_itm_api.o
#OBJECTS += ./mbed-os/hal/mbed_lp_ticker_api.o
#OBJECTS += ./mbed-os/hal/mbed_lp_ticker_wrapper.o
#OBJECTS += ./mbed-os/hal/mbed_pinmap_common.o
#OBJECTS += ./mbed-os/hal/mbed_pinmap_default.o
#OBJECTS += ./mbed-os/hal/mbed_ticker_api.o
#OBJECTS += ./mbed-os/hal/mbed_us_ticker_api.o
#OBJECTS += ./mbed-os/hal/mpu/mbed_mpu_v7m.o
#OBJECTS += ./mbed-os/hal/mpu/mbed_mpu_v8m.o
#OBJECTS += ./mbed-os/hal/usb/mbed_usb_phy.o
#OBJECTS += ./mbed-os/platform/SysTimer.o
#OBJECTS += ./mbed-os/platform/cxxsupport/mstd_mutex.o
#OBJECTS += ./mbed-os/platform/mbed_os_timer.o
#OBJECTS += ./mbed-os/platform/mbed_thread.o
#OBJECTS += ./mbed-os/platform/source/ATCmdParser.o
#OBJECTS += ./mbed-os/platform/source/CThunkBase.o
#OBJECTS += ./mbed-os/platform/source/CallChain.o
#OBJECTS += ./mbed-os/platform/source/CriticalSectionLock.o
#OBJECTS += ./mbed-os/platform/source/DeepSleepLock.o
#OBJECTS += ./mbed-os/platform/source/FileBase.o
#OBJECTS += ./mbed-os/platform/source/FileHandle.o
#OBJECTS += ./mbed-os/platform/source/FilePath.o
#OBJECTS += ./mbed-os/platform/source/FileSystemHandle.o
#OBJECTS += ./mbed-os/platform/source/LocalFileSystem.o
#OBJECTS += ./mbed-os/platform/source/Stream.o
#OBJECTS += ./mbed-os/platform/source/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.o
#OBJECTS += ./mbed-os/platform/source/TARGET_CORTEX_M/mbed_fault_handler.o
#OBJECTS += ./mbed-os/platform/source/mbed_alloc_wrappers.o
#OBJECTS += ./mbed-os/platform/source/mbed_application.o
#OBJECTS += ./mbed-os/platform/source/mbed_assert.o
#OBJECTS += ./mbed-os/platform/source/mbed_atomic_impl.o
#OBJECTS += ./mbed-os/platform/source/mbed_board.o
#OBJECTS += ./mbed-os/platform/source/mbed_critical.o
#OBJECTS += ./mbed-os/platform/source/mbed_error.o
#OBJECTS += ./mbed-os/platform/source/mbed_error_hist.o
#OBJECTS += ./mbed-os/platform/source/mbed_interface.o
#OBJECTS += ./mbed-os/platform/source/mbed_mem_trace.o
#OBJECTS += ./mbed-os/platform/source/mbed_mktime.o
#OBJECTS += ./mbed-os/platform/source/mbed_mpu_mgmt.o
#OBJECTS += ./mbed-os/platform/source/mbed_poll.o
#OBJECTS += ./mbed-os/platform/source/mbed_power_mgmt.o
#OBJECTS += ./mbed-os/platform/source/mbed_retarget.o
#OBJECTS += ./mbed-os/platform/source/mbed_rtc_time.o
#OBJECTS += ./mbed-os/platform/source/mbed_sdk_boot.o
#OBJECTS += ./mbed-os/platform/source/mbed_semihost_api.o
#OBJECTS += ./mbed-os/platform/source/mbed_stats.o
#OBJECTS += ./mbed-os/platform/source/mbed_wait_api_no_rtos.o
#OBJECTS += ./mbed-os/platform/source/mbed_wait_api_rtos.o
#OBJECTS += ./mbed-os/platform/source/minimal-printf/mbed_printf_armlink_overrides.o
#OBJECTS += ./mbed-os/platform/source/minimal-printf/mbed_printf_implementation.o
#OBJECTS += ./mbed-os/platform/source/minimal-printf/mbed_printf_wrapper.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PeripheralPins.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/system_clock.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM/startup_stm32f767xx.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/analogin_device.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/analogout_device.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_adc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_adc_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_can.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_can_legacy.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cec.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cortex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_crc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_crc_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cryp.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cryp_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dac.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dac_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dcmi.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dcmi_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dfsdm.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma2d.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dsi.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_eth.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_flash.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_flash_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_gpio.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hash.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hash_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hcd.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2c.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2c_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2s.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_irda.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_iwdg.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_jpeg.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_lptim.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_ltdc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_ltdc_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_mdios.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_mmc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_nand.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_nor.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pwr.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pwr_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_qspi.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rcc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rcc_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rng.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rtc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rtc_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sai.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sai_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sd.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sdram.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smartcard.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smartcard_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smbus.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spdifrx.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spi.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spi_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sram.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_tim.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_tim_ex.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_uart.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_usart.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_wwdg.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_adc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_crc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dac.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dma.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dma2d.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_exti.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_fmc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_gpio.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_i2c.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_lptim.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_pwr.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rcc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rng.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rtc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_sdmmc.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_spi.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_tim.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_usart.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_usb.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_utils.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/device/system_stm32f7xx.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/flash_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/gpio_irq_device.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/pwmout_device.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/serial_device.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/spi_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/USBPhy_STM32.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/analogin_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/analogout_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/can_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/gpio_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/gpio_irq_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/hal_tick_overrides.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/i2c_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/lp_ticker.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/mbed_crc_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/mbed_overrides.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/pinmap.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/port_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/pwmout_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/qspi_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/reset_reason.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/rtc_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/serial_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/sleep.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/stm_spi_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/trng_api.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/us_ticker.o
#OBJECTS += ./mbed-os/targets/TARGET_STM/watchdog_api.o

OBJECTS += ./tensorflow/tensorflow/lite/c/common.o
OBJECTS += ./tensorflow/tensorflow/lite/core/api/error_reporter.o
OBJECTS += ./tensorflow/tensorflow/lite/core/api/flatbuffer_conversions.o
OBJECTS += ./tensorflow/tensorflow/lite/core/api/op_resolver.o
OBJECTS += ./tensorflow/tensorflow/lite/core/api/tensor_utils.o
OBJECTS += ./tensorflow/tensorflow/lite/kernels/internal/quantization_util.o
OBJECTS += ./tensorflow/tensorflow/lite/kernels/kernel_util.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/all_ops_resolver.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/benchmarks/keyword_scrambled_model_data.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/activations.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/arg_min_max.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/ceil.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/circular_buffer.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/cmsis-nn/add.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/cmsis-nn/conv.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/cmsis-nn/depthwise_conv.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/cmsis-nn/fully_connected.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/cmsis-nn/mul.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/cmsis-nn/pooling.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/cmsis-nn/softmax.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/comparisons.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/concatenation.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/dequantize.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/elementwise.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/ethosu.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/floor.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/l2norm.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/logical.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/logistic.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/neg.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/pack.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/pad.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/prelu.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/quantize.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/reduce.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/reshape.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/round.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/split.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/strided_slice.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/sub.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/svdf.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/tanh.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/kernels/unpack.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/memory_helpers.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/memory_planner/greedy_memory_planner.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/memory_planner/linear_memory_planner.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/micro_allocator.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/micro_error_reporter.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/micro_interpreter.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/micro_optional_debug_tools.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/micro_profiler.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/micro_string.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/micro_time.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/micro_utils.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/recording_micro_allocator.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/recording_simple_memory_allocator.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/simple_memory_allocator.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/test_helpers.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/testing/test_conv_model.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/testing/test_utils.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ActivationFunctions/arm_nn_activations_q15.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ActivationFunctions/arm_nn_activations_q7.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ActivationFunctions/arm_relu6_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ActivationFunctions/arm_relu_q15.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ActivationFunctions/arm_relu_q7.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_w.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_x.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_y.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_z.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_basic.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_wrapper_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_u8_basic_ver1.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_depthwise_conv_s8_core.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15_reordered.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15_opt.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15_opt.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7_opt.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_accumulate_q7_to_q15.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_add_q7.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_padded_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_4x_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q15.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q7.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nntables.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_no_shift.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_no_shift.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8_opt.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/PoolingFunctions/arm_pool_q7_HWC.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ReshapeFunctions/arm_reshape_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_q15.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_q7.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_s8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_u8.o
OBJECTS += ./tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_with_batch_q7.o

OBJECTS += ./projects/mbed_test/constants.o
OBJECTS += ./projects/mbed_test/full_quant_model.o
OBJECTS += ./projects/mbed_test/images/images.o
OBJECTS += ./projects/mbed_test/main.o
OBJECTS += ./projects/mbed_test/printf.o
OBJECTS += ./projects/mbed_test/sys_init.o
OBJECTS += ./projects/mbed_test/utility.o
OBJECTS += ./projects/mbed_test/model_settings.o
OBJECTS += ./projects/mbed_test/debug_log.o


INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I.././mbed-os
INCLUDE_PATHS += -I.././mbed-os/cmsis
INCLUDE_PATHS += -I.././mbed-os/cmsis/TARGET_CORTEX_M
INCLUDE_PATHS += -I.././mbed-os/components
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/atmel-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/mcr20a-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/storage/blockdevice/COMPONENT_FLASHIAP
INCLUDE_PATHS += -I.././mbed-os/components/wifi
INCLUDE_PATHS += -I.././mbed-os/components/wifi/esp8266-driver
INCLUDE_PATHS += -I.././mbed-os/drivers
INCLUDE_PATHS += -I.././mbed-os/drivers/internal
INCLUDE_PATHS += -I.././mbed-os/events
INCLUDE_PATHS += -I.././mbed-os/features
INCLUDE_PATHS += -I.././mbed-os/features/cellular
INCLUDE_PATHS += -I.././mbed-os/features/device_key
INCLUDE_PATHS += -I.././mbed-os/features/frameworks
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/greentea-client
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/mbed-client-cli
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/mbed-client-randlib
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/mbed-coap
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/mbed-trace
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/nanostack-libservice
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/unity
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/utest
INCLUDE_PATHS += -I.././mbed-os/features/lorawan
INCLUDE_PATHS += -I.././mbed-os/features/lwipstack
INCLUDE_PATHS += -I.././mbed-os/features/mbedtls
INCLUDE_PATHS += -I.././mbed-os/features/nanostack
INCLUDE_PATHS += -I.././mbed-os/features/nanostack/coap-service
INCLUDE_PATHS += -I.././mbed-os/features/nanostack/mbed-mesh-api
INCLUDE_PATHS += -I.././mbed-os/features/nanostack/nanostack-hal-mbed-cmsis-rtos
INCLUDE_PATHS += -I.././mbed-os/features/nanostack/nanostack-interface
INCLUDE_PATHS += -I.././mbed-os/features/nanostack/sal-stack-nanostack
INCLUDE_PATHS += -I.././mbed-os/features/nanostack/sal-stack-nanostack-eventloop
INCLUDE_PATHS += -I.././mbed-os/features/netsocket
INCLUDE_PATHS += -I.././mbed-os/features/nfc
INCLUDE_PATHS += -I.././mbed-os/features/storage
INCLUDE_PATHS += -I.././mbed-os/features/storage/blockdevice
INCLUDE_PATHS += -I.././mbed-os/features/storage/filesystem
INCLUDE_PATHS += -I.././mbed-os/features/storage/kvstore
INCLUDE_PATHS += -I.././mbed-os/features/storage/kvstore/conf
INCLUDE_PATHS += -I.././mbed-os/features/storage/kvstore/direct_access_devicekey
INCLUDE_PATHS += -I.././mbed-os/features/storage/kvstore/filesystemstore
INCLUDE_PATHS += -I.././mbed-os/features/storage/kvstore/global_api
INCLUDE_PATHS += -I.././mbed-os/features/storage/kvstore/include
INCLUDE_PATHS += -I.././mbed-os/features/storage/kvstore/kv_map
INCLUDE_PATHS += -I.././mbed-os/features/storage/kvstore/securestore
INCLUDE_PATHS += -I.././mbed-os/features/storage/kvstore/tdbstore
INCLUDE_PATHS += -I.././mbed-os/features/storage/nvstore
INCLUDE_PATHS += -I.././mbed-os/features/storage/system_storage
INCLUDE_PATHS += -I.././mbed-os/hal
INCLUDE_PATHS += -I.././mbed-os/hal/storage_abstraction
INCLUDE_PATHS += -I.././mbed-os/hal/usb
INCLUDE_PATHS += -I.././mbed-os/platform
INCLUDE_PATHS += -I.././mbed-os/platform/cxxsupport
INCLUDE_PATHS += -I.././mbed-os/platform/internal
INCLUDE_PATHS += -I.././mbed-os/platform/source
INCLUDE_PATHS += -I.././mbed-os/platform/source/TARGET_CORTEX_M
INCLUDE_PATHS += -I.././mbed-os/platform/source/minimal-printf
INCLUDE_PATHS += -I.././mbed-os/rtos
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7/device

INCLUDE_PATHS += -I.././tensorflow
INCLUDE_PATHS += -I.././tensorflow/tensorflow/core
INCLUDE_PATHS += -I.././tensorflow/tensorflow/core/public
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/c
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/core
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/core/api
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/kernels
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/kernels/internal
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/kernels/internal/optimized
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/kernels/internal/reference
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/kernels/internal/reference/integer_ops
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/benchmarks
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/examples
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/examples/hello_world
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/examples/hello_world/images
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/kernels
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/memory_planner
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/testing
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/tools
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/tools/make
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/tools/make/downloads
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Include
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include
INCLUDE_PATHS += -I.././tensorflow/tensorflow/lite/schema
INCLUDE_PATHS += -I.././third_party
INCLUDE_PATHS += -I.././third_party/flatbuffers
INCLUDE_PATHS += -I.././third_party/flatbuffers/include
INCLUDE_PATHS += -I.././third_party/flatbuffers/include/flatbuffers
INCLUDE_PATHS += -I.././third_party/gemmlowp
INCLUDE_PATHS += -I.././third_party/gemmlowp/fixedpoint
INCLUDE_PATHS += -I.././third_party/gemmlowp/internal
INCLUDE_PATHS += -I.././third_party/kissfft
INCLUDE_PATHS += -I.././third_party/kissfft/tools
INCLUDE_PATHS += -I.././third_party/ruy
INCLUDE_PATHS += -I.././third_party/ruy/ruy
INCLUDE_PATHS += -I.././third_party/ruy/ruy/profiler
INCLUDE_PATHS += -I..//home/skobec/work/hello_world/mbed/mbed-os

LIBRARY_PATHS :=
LIBRARIES :=
#LINKER_SCRIPT ?= .././mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM/STM32F767xI.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = arm-none-eabi-gcc
CC      = arm-none-eabi-gcc
CPP     = arm-none-eabi-g++
LD      = arm-none-eabi-gcc
ELF2BIN = arm-none-eabi-objcopy
PREPROC = arm-none-eabi-cpp -E -P -Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=softfp -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x200000 -DMBED_ROM1_START=0x200000 -DMBED_ROM1_SIZE=0x200000 -DMBED_RAM_START=0x20020000 -DMBED_RAM_SIZE=0x60000 -DMBED_RAM1_START=0x20000000 -DMBED_RAM1_SIZE=0x20000 -DMBED_BOOT_STACK_SIZE=4096


C_FLAGS += -std=gnu11
C_FLAGS += -include
C_FLAGS += mbed_config.h
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -DTARGET_STM
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DTARGET_FF_ARDUINO
C_FLAGS += -DTARGET_STM32F767ZI
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DTARGET_FAMILY_STM32
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DDEVICE_LPTICKER=1
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DARM_MATH_CM7
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DTARGET_RTOS_M4_M7
C_FLAGS += -DDEVICE_RESET_REASON=1
C_FLAGS += -DTARGET_STM32F767xI
C_FLAGS += -DTARGET_STM_EMAC
C_FLAGS += -DDEVICE_WATCHDOG=1
C_FLAGS += -DDEVICE_EMAC=1
C_FLAGS += -DTARGET_STM32F767
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1602246971.1649482
C_FLAGS += -DDEVICE_MPU=1
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -D__CORTEX_M7
C_FLAGS += -DCOMPONENT_PSA_SRV_EMUL=1
C_FLAGS += -DCOMPONENT_NSPE=1
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -D__FPU_PRESENT=1
C_FLAGS += -DTARGET_M7
C_FLAGS += -DTARGET_NAME=NUCLEO_F767ZI
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -DCOMPONENT_FLASHIAP=1
C_FLAGS += -DDEVICE_SERIAL_FC=1
C_FLAGS += -DUSBHOST_OTHER
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
C_FLAGS += -DMBED_TICKLESS
C_FLAGS += -DDEVICE_ANALOGOUT=1
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_USBDEVICE=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DUSE_HAL_DRIVER
C_FLAGS += -DCOMPONENT_PSA_SRV_IMPL=1
C_FLAGS += -DEXTRA_IDLE_STACK_REQUIRED
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -D__MBED__=1
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DDEVICE_FLASH=1
C_FLAGS += -DTARGET_NUCLEO_F767ZI
C_FLAGS += -DDEVICE_CAN=1
C_FLAGS += -DDEVICE_TRNG=1
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -DDEVICE_USTICKER=1
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DUSE_FULL_LL_DRIVER
C_FLAGS += -DTARGET_LIKE_CORTEX_M7
C_FLAGS += -DDEVICE_CRC=1
C_FLAGS += -DTARGET_STM32F7
C_FLAGS += -include
C_FLAGS += mbed_config.h
C_FLAGS += -std=gnu11
C_FLAGS += -c
C_FLAGS += -Wall
C_FLAGS += -Wextra
C_FLAGS += -Wno-unused-parameter
C_FLAGS += -Wno-missing-field-initializers
C_FLAGS += -fmessage-length=0
C_FLAGS += -fno-exceptions
C_FLAGS += -ffunction-sections
C_FLAGS += -fdata-sections
C_FLAGS += -funsigned-char
C_FLAGS += -MMD
C_FLAGS += -fno-delete-null-pointer-checks
C_FLAGS += -fomit-frame-pointer
C_FLAGS += -O3
#C_FLAGS += -g
C_FLAGS += -DMBED_DEBUG
C_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
C_FLAGS += -mcpu=cortex-m7
C_FLAGS += -mthumb
C_FLAGS += -mfpu=fpv5-sp-d16
C_FLAGS += -mfloat-abi=hard
C_FLAGS += -DMBED_ROM_START=0x8000000
C_FLAGS += -DMBED_ROM_SIZE=0x200000
C_FLAGS += -DMBED_ROM1_START=0x200000
C_FLAGS += -DMBED_ROM1_SIZE=0x200000
C_FLAGS += -DMBED_RAM_START=0x20020000
C_FLAGS += -DMBED_RAM_SIZE=0x60000
C_FLAGS += -DMBED_RAM1_START=0x20000000
C_FLAGS += -DMBED_RAM1_SIZE=0x20000
C_FLAGS += -Wno-narrowing

CXX_FLAGS += -std=gnu++14
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -DTARGET_STM
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DTARGET_FF_ARDUINO
CXX_FLAGS += -DTARGET_STM32F767ZI
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DTARGET_FAMILY_STM32
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DDEVICE_LPTICKER=1
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DARM_MATH_CM7
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DTARGET_RTOS_M4_M7
CXX_FLAGS += -DDEVICE_RESET_REASON=1
CXX_FLAGS += -DTARGET_STM32F767xI
CXX_FLAGS += -DTARGET_STM_EMAC
CXX_FLAGS += -DDEVICE_WATCHDOG=1
CXX_FLAGS += -DDEVICE_EMAC=1
CXX_FLAGS += -DTARGET_STM32F767
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1602246971.1649482
CXX_FLAGS += -DDEVICE_MPU=1
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -D__CORTEX_M7
CXX_FLAGS += -DCOMPONENT_PSA_SRV_EMUL=1
CXX_FLAGS += -DCOMPONENT_NSPE=1
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -D__FPU_PRESENT=1
CXX_FLAGS += -DTARGET_M7
CXX_FLAGS += -DTARGET_NAME=NUCLEO_F767ZI
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -DCOMPONENT_FLASHIAP=1
CXX_FLAGS += -DDEVICE_SERIAL_FC=1
CXX_FLAGS += -DUSBHOST_OTHER
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
CXX_FLAGS += -DMBED_TICKLESS
CXX_FLAGS += -DDEVICE_ANALOGOUT=1
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_USBDEVICE=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DUSE_HAL_DRIVER
CXX_FLAGS += -DCOMPONENT_PSA_SRV_IMPL=1
CXX_FLAGS += -DEXTRA_IDLE_STACK_REQUIRED
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DDEVICE_FLASH=1
CXX_FLAGS += -DTARGET_NUCLEO_F767ZI
CXX_FLAGS += -DDEVICE_CAN=1
CXX_FLAGS += -DDEVICE_TRNG=1
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -DDEVICE_USTICKER=1
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DUSE_FULL_LL_DRIVER
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M7
CXX_FLAGS += -DDEVICE_CRC=1
CXX_FLAGS += -DTARGET_STM32F7
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h
CXX_FLAGS += -std=gnu++14
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -c
CXX_FLAGS += -Wall
CXX_FLAGS += -Wextra
CXX_FLAGS += -Wno-unused-parameter
CXX_FLAGS += -Wno-missing-field-initializers
CXX_FLAGS += -fmessage-length=0
CXX_FLAGS += -fno-exceptions
CXX_FLAGS += -ffunction-sections
CXX_FLAGS += -fdata-sections
CXX_FLAGS += -funsigned-char
CXX_FLAGS += -MMD
CXX_FLAGS += -fno-delete-null-pointer-checks
CXX_FLAGS += -fomit-frame-pointer
CXX_FLAGS += -O3
#CXX_FLAGS += -g
CXX_FLAGS += -DMBED_DEBUG
CXX_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
CXX_FLAGS += -mcpu=cortex-m7
CXX_FLAGS += -mthumb
CXX_FLAGS += -mfpu=fpv5-sp-d16
CXX_FLAGS += -mfloat-abi=hard
CXX_FLAGS += -DMBED_ROM_START=0x8000000
CXX_FLAGS += -DMBED_ROM_SIZE=0x200000
CXX_FLAGS += -DMBED_ROM1_START=0x200000
CXX_FLAGS += -DMBED_ROM1_SIZE=0x200000
CXX_FLAGS += -DMBED_RAM_START=0x20020000
CXX_FLAGS += -DMBED_RAM_SIZE=0x60000
CXX_FLAGS += -DMBED_RAM1_START=0x20000000
CXX_FLAGS += -DMBED_RAM1_SIZE=0x20000
CXX_FLAGS += -Wno-narrowing
#CXX_FLAGS += -fno-use-cxa-atexit
CXX_FLAGS += -fno-threadsafe-statics

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -DUSBHOST_OTHER
ASM_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
ASM_FLAGS += -DMBED_TICKLESS
ASM_FLAGS += -D__CORTEX_M7
ASM_FLAGS += -DARM_MATH_CM7
ASM_FLAGS += -DUSE_FULL_LL_DRIVER
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -DUSE_HAL_DRIVER
ASM_FLAGS += -D__FPU_PRESENT=1
ASM_FLAGS += -DEXTRA_IDLE_STACK_REQUIRED
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -I..
ASM_FLAGS += -I../mbed-os
ASM_FLAGS += -I../mbed-os/cmsis
ASM_FLAGS += -I../mbed-os/cmsis/TARGET_CORTEX_M
ASM_FLAGS += -I../mbed-os/components
ASM_FLAGS += -I../mbed-os/components/802.15.4_RF
ASM_FLAGS += -I../mbed-os/components/802.15.4_RF/atmel-rf-driver
ASM_FLAGS += -I../mbed-os/components/802.15.4_RF/mcr20a-rf-driver
ASM_FLAGS += -I../mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver
ASM_FLAGS += -I../mbed-os/components/storage/blockdevice/COMPONENT_FLASHIAP
ASM_FLAGS += -I../mbed-os/components/wifi
ASM_FLAGS += -I../mbed-os/components/wifi/esp8266-driver
ASM_FLAGS += -I../mbed-os/drivers
ASM_FLAGS += -I../mbed-os/drivers/internal
ASM_FLAGS += -I../mbed-os/events
ASM_FLAGS += -I../mbed-os/features
ASM_FLAGS += -I../mbed-os/features/cellular
ASM_FLAGS += -I../mbed-os/features/device_key
ASM_FLAGS += -I../mbed-os/features/frameworks
ASM_FLAGS += -I../mbed-os/features/frameworks/greentea-client
ASM_FLAGS += -I../mbed-os/features/frameworks/mbed-client-cli
ASM_FLAGS += -I../mbed-os/features/frameworks/mbed-client-randlib
ASM_FLAGS += -I../mbed-os/features/frameworks/mbed-coap
ASM_FLAGS += -I../mbed-os/features/frameworks/mbed-trace
ASM_FLAGS += -I../mbed-os/features/frameworks/nanostack-libservice
ASM_FLAGS += -I../mbed-os/features/frameworks/unity
ASM_FLAGS += -I../mbed-os/features/frameworks/utest
ASM_FLAGS += -I../mbed-os/features/lorawan
ASM_FLAGS += -I../mbed-os/features/lwipstack
ASM_FLAGS += -I../mbed-os/features/mbedtls
ASM_FLAGS += -I../mbed-os/features/nanostack
ASM_FLAGS += -I../mbed-os/features/nanostack/coap-service
ASM_FLAGS += -I../mbed-os/features/nanostack/mbed-mesh-api
ASM_FLAGS += -I../mbed-os/features/nanostack/nanostack-hal-mbed-cmsis-rtos
ASM_FLAGS += -I../mbed-os/features/nanostack/nanostack-interface
ASM_FLAGS += -I../mbed-os/features/nanostack/sal-stack-nanostack
ASM_FLAGS += -I../mbed-os/features/nanostack/sal-stack-nanostack-eventloop
ASM_FLAGS += -I../mbed-os/features/netsocket
ASM_FLAGS += -I../mbed-os/features/nfc
ASM_FLAGS += -I../mbed-os/features/storage
ASM_FLAGS += -I../mbed-os/features/storage/blockdevice
ASM_FLAGS += -I../mbed-os/features/storage/filesystem
ASM_FLAGS += -I../mbed-os/features/storage/kvstore
ASM_FLAGS += -I../mbed-os/features/storage/kvstore/conf
ASM_FLAGS += -I../mbed-os/features/storage/kvstore/direct_access_devicekey
ASM_FLAGS += -I../mbed-os/features/storage/kvstore/filesystemstore
ASM_FLAGS += -I../mbed-os/features/storage/kvstore/global_api
ASM_FLAGS += -I../mbed-os/features/storage/kvstore/include
ASM_FLAGS += -I../mbed-os/features/storage/kvstore/kv_map
ASM_FLAGS += -I../mbed-os/features/storage/kvstore/securestore
ASM_FLAGS += -I../mbed-os/features/storage/kvstore/tdbstore
ASM_FLAGS += -I../mbed-os/features/storage/nvstore
ASM_FLAGS += -I../mbed-os/features/storage/system_storage
ASM_FLAGS += -I../mbed-os/hal
ASM_FLAGS += -I../mbed-os/hal/storage_abstraction
ASM_FLAGS += -I../mbed-os/hal/usb
ASM_FLAGS += -I../mbed-os/platform
ASM_FLAGS += -I../mbed-os/platform/cxxsupport
ASM_FLAGS += -I../mbed-os/platform/internal
ASM_FLAGS += -I../mbed-os/platform/source
ASM_FLAGS += -I../mbed-os/platform/source/TARGET_CORTEX_M
ASM_FLAGS += -I../mbed-os/platform/source/minimal-printf
ASM_FLAGS += -I../mbed-os/rtos
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7/device
ASM_FLAGS += -I../tensorflow
ASM_FLAGS += -I../tensorflow/core
ASM_FLAGS += -I../tensorflow/core/public
ASM_FLAGS += -I../tensorflow/lite
ASM_FLAGS += -I../tensorflow/lite/c
ASM_FLAGS += -I../tensorflow/lite/core
ASM_FLAGS += -I../tensorflow/lite/core/api
ASM_FLAGS += -I../tensorflow/lite/kernels
ASM_FLAGS += -I../tensorflow/lite/kernels/internal
ASM_FLAGS += -I../tensorflow/lite/kernels/internal/optimized
ASM_FLAGS += -I../tensorflow/lite/kernels/internal/reference
ASM_FLAGS += -I../tensorflow/lite/kernels/internal/reference/integer_ops
ASM_FLAGS += -I../tensorflow/lite/micro
ASM_FLAGS += -I../tensorflow/lite/micro/benchmarks
ASM_FLAGS += -I../tensorflow/lite/micro/examples
ASM_FLAGS += -I../tensorflow/lite/micro/examples/hello_world
ASM_FLAGS += -I../tensorflow/lite/micro/examples/hello_world/images
ASM_FLAGS += -I../tensorflow/lite/micro/kernels
ASM_FLAGS += -I../tensorflow/lite/micro/memory_planner
ASM_FLAGS += -I../tensorflow/lite/micro/testing
ASM_FLAGS += -I../tensorflow/lite/micro/tools
ASM_FLAGS += -I../tensorflow/lite/micro/tools/make
ASM_FLAGS += -I../tensorflow/lite/micro/tools/make/downloads
ASM_FLAGS += -I../tensorflow/lite/micro/tools/make/downloads/cmsis
ASM_FLAGS += -I../tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS
ASM_FLAGS += -I../tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP
ASM_FLAGS += -I../tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Include
ASM_FLAGS += -I../tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN
ASM_FLAGS += -I../tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include
ASM_FLAGS += -I../tensorflow/lite/schema
ASM_FLAGS += -I../third_party
ASM_FLAGS += -I../third_party/flatbuffers
ASM_FLAGS += -I../third_party/flatbuffers/include
ASM_FLAGS += -I../third_party/flatbuffers/include/flatbuffers
ASM_FLAGS += -I../third_party/gemmlowp
ASM_FLAGS += -I../third_party/gemmlowp/fixedpoint
ASM_FLAGS += -I../third_party/gemmlowp/internal
ASM_FLAGS += -I../third_party/kissfft
ASM_FLAGS += -I../third_party/kissfft/tools
ASM_FLAGS += -I../third_party/ruy
ASM_FLAGS += -I../third_party/ruy/ruy
ASM_FLAGS += -I../third_party/ruy/ruy/profiler
ASM_FLAGS += -I/home/skobec/work/hello_world/mbed/mbed-os
ASM_FLAGS += -include
ASM_FLAGS += ./mbed_config.h
ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -c
ASM_FLAGS += -Wall
ASM_FLAGS += -Wextra
ASM_FLAGS += -Wno-unused-parameter
ASM_FLAGS += -Wno-missing-field-initializers
ASM_FLAGS += -fmessage-length=0
ASM_FLAGS += -fno-exceptions
ASM_FLAGS += -ffunction-sections
ASM_FLAGS += -fdata-sections
ASM_FLAGS += -funsigned-char
ASM_FLAGS += -MMD
ASM_FLAGS += -fno-delete-null-pointer-checks
ASM_FLAGS += -fomit-frame-pointer
ASM_FLAGS += -O3
#ASM_FLAGS += -g
ASM_FLAGS += -DMBED_DEBUG
ASM_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
ASM_FLAGS += -mcpu=cortex-m7
ASM_FLAGS += -mthumb
ASM_FLAGS += -mfpu=fpv5-sp-d16
ASM_FLAGS += -mfloat-abi=hard
ASM_FLAGS += -Wno-narrowing
 

C_FLAGS   += -DSTM32F7 -DSTM32F7CCM -DSTM32F767ZI -I.././libopencm3/include
CXX_FLAGS += -DSTM32F7 -DSTM32F7CCM -DSTM32F767ZI -I.././libopencm3/include
ASM_FLAGS += -DSTM32F7 -DSTM32F7CCM -DSTM32F767ZI -I.././libopencm3/include

INCLUDE_PATHS += -I.././libopencm3/include
INCLUDE_PATHS += -I.././libopencm3/lib
LDLIBS := .././libopencm3/lib/libopencm3_stm32f7.a
LDSCRIPT := ../projects/mbed_test/linker_script.ld



#LD_FLAGS :=-Wl,--gc-sections -Wl,-n -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=hard -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x200000 -DMBED_ROM1_START=0x200000 -DMBED_ROM1_SIZE=0x200000 -DMBED_RAM_START=0x20020000 -DMBED_RAM_SIZE=0x60000 -DMBED_RAM1_START=0x20000000 -DMBED_RAM1_SIZE=0x20000 -DMBED_BOOT_STACK_SIZE=4096 
#LD_FLAGS += \
#-nostartfiles \
#-specs=nano.specs \
#-specs=nosys.specs
#
#LD_FLAGS +=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group

ARCH_FLAGS := -mcpu=cortex-m7
ARCH_FLAGS += -mthumb
ARCH_FLAGS += -mfpu=fpv5-sp-d16
ARCH_FLAGS += -mfloat-abi=hard

LIBS := -Wl,--start-group -lc -lgcc -lm -lnosys -Wl,--end-group

LDFLAGS +=  \
$(ARCH_FLAGS) \
-nostartfiles \
-specs=nano.specs \
-specs=nosys.specs \
-L$(OPENCM3_DIR)/lib \
-T$(LDSCRIPT) \
$(LIBS) \
-Wl,--gc-sections \
-Wl,--no-wchar-size-warning \
-funsigned-char \
-ffunction-sections \
-fdata-sections \
-fno-common \
-static  \
$(OPT) \

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cc.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<

#$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
#Jk	@$(PREPROC) $< -o $@


#$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 

#+@echo "$(filter %.o, $^)" > .link_options.txt

	#+@echo "link: $(notdir $@)"
	#@$(LD) $(LD_FLAGS) -T$(LINKER_SCRIPT) $(LIBRARIES) $(OBJECTS) $(INCLUDE_PATHS)

$(PROJECT).elf: $(OBJECTS)
	@printf "  LD\t$@\n"
	@$(LD) $(OBJECTS) $(LDFLAGS) $(INCLUDE_PATHS) $(LDLIBS) -o $@

$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# It is expected that a openocd.cfg file is in project folder
flash:
	openocd -f ../openocd.cfg

monitor: $(PROJECT).elf
	openocd -f ../openocd.cfg
	minicom


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
